import type { Metadata } from "next";
// import { Inter } from "next/font/google";
import Header from "@/components/client/Header";
import Side from "@/components/client/SIde";
import { AntdRegistry } from '@ant-design/nextjs-registry';
import Style from "./layout.module.css";
import "./globals.scss";

// const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App 1",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  /** 在这里请求一些公有的东西 */
  /** 请求用户信息 */
  return (
    <html lang="en">
      <body>
        <AntdRegistry>
            <Header />
            <Side />
            <div className={Style.container}>
              {children}
            </div>
        </AntdRegistry>
      </body>
    </html>
  );
}
